# Generated by Django 6.0.4 on 2026-04-25 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reminder_reminderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='note',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='note',
            name='sender',
        ),
        migrations.AddField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
