# Generated by Django 6.0.4 on 2026-04-25 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_note_is_read_remove_note_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mood_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
