# Generated by Django 6.0.4 on 2026-04-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_mood_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='checked_on',
            field=models.BooleanField(default=False),
        ),
    ]
